### ISSUE TITLE
compose problem

### ISSUE THREAD

**Issue by caglaryalcin** [dh1011/subscription-manager#15]
Hi,
What is the problem with the following compose file? The container stands up, but I can't access it through port 3541.

```yaml
services:
  submanager:
    image: dh1011/subscription-manager:1.0.0
    container_name: subs-manager
    ports:
      - 3541:3000
    environment:
      NODE_ENV: production
      HOST: 10.0.0.100
    volumes:
      - /docker/submanager/subscriptions.db:/app/subscriptions.db:rw
    restart: on-failure:5
    networks:
      - subscription_network

networks:
  subscription_network:
    name: subscription
    ipam:
      config:
        - subnet: 172.53.0.0/24
```

Container logs:

```log
> subscription-manager@0.1.0 dev
> concurrently "npm run server" "npm run client"
[0] 
[0] > subscription-manager@0.1.0 server
[0] > node server/server.js
[0] 
[1] 
[1] > subscription-manager@0.1.0 client
[1] > react-scripts start
[1] 
[0] Using subscriptions database located at: /app/server/subscriptions.db due to baseDir: /app/server
[0] Server running on port 5000
[0] Database initialized successfully with new table for user configuration.
[1] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
[1]  - options.allowedHosts[0] should be a non-empty string.
[1] npm run client exited with code 1
```
