### ISSUE TITLE
container problem

### ISSUE THREAD

**Issue by caglaryalcin** [dh1011/subscription-manager#6]
Hello,
I'm getting an error when I do the following compose. I've attached the container log. What could be the problem?

```yaml
services:
 submanager:
  image: dh1011/subscription-manager:1.0.0
  container_name: subs-manager
  healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
  ports:
   - 3541:3000
  environment:
   NODE_ENV: production
   HOST: 0.0.0.0
  volumes:
   - /volume1/docker/submanager/subscriptions.db:/app/subscriptions.db:rw
  restart: on-failure:5
  networks:
      - subscription_network

networks:
  subscription_network:
    name: subscription
    ipam:
      config:
        - subnet: 172.53.0.0/24
```

container logs:
```log
> subscription-manager@0.1.0 dev
> concurrently "npm run server" "npm run client"
[0] 
[0] > subscription-manager@0.1.0 server
[0] > node server/server.js
[0] 
[1] 
[1] > subscription-manager@0.1.0 client
[1] > react-scripts start
[1] 
[0] Server running on port 5000
[0] Database initialized successfully
[1] Attempting to bind to HOST environment variable: 0.0.0.0
[1] If this was unintentional, check that you haven't mistakenly set it in your shell.
[1] Learn more here: https://cra.link/advanced-config
[1] 
[1] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
[1]  - options.allowedHosts[0] should be a non-empty string.
[1] npm run client exited with code 1
npm error path /app
npm error command failed
npm error signal SIGTERM
npm error command sh -c concurrently "npm run server" "npm run client"
npm error A complete log of this run can be found in: /root/.npm/_logs/2024-10-07T12_49_46_522Z-debug-0.log
> subscription-manager@0.1.0 dev
> concurrently "npm run server" "npm run client"
[0] 
[0] > subscription-manager@0.1.0 server
[0] > node server/server.js
[0] 
[1] 
[1] > subscription-manager@0.1.0 client
[1] > react-scripts start
[1] 
[0] Server running on port 5000
[0] Database initialized successfully
[1] Attempting to bind to HOST environment variable: 0.0.0.0
[1] If this was unintentional, check that you haven't mistakenly set it in your shell.
[1] Learn more here: https://cra.link/advanced-config
[1] 
[1] Invalid options object. Dev Server has been initialized using an options object that does not match the API schema.
[1]  - options.allowedHosts[0] should be a non-empty string.
[1] npm run client exited with code 1
```
